### ISSUE TITLE
Dig mix resets to zero

### ISSUE THREAD

**Issue by losikid** [semerad/gt3b#1]
When using dig after it stops displaying the rate it will return to 0% mix (even mix). It would be more ideal if it kept that rate as many people drive most the time at a certain rate. So always reverting back to zero can cause problems.

**Comment by semerad** [comment]
> When using dig after it stops displaying the rate it will return to 0%
> mix (even mix). It would be more ideal if it kept that rate as many
> people drive most the time at a certain rate. So always reverting back
> to zero can cause problems.

  I don't understand it. Write exactly what are You doing and how
exactly You did setup those keys. There is too many possibilities how it
can be setup.

**Comment by losikid** [comment]
I had the ch 3 trim set as dig with the mom mode

D/r was setup as Dig and the end mode.

Look at the end of this video

http://www.youtube.com/watch?v=v7dGifwCvtw

It also did it when i was simply controlling the 3rd channel.

**Comment by semerad** [comment]
> I had the ch 3 trim set as dig with the mom mode
> 
> D/r was setup as Dig and the end mode.
> 
> Look at the end of this video
> 
> http://www.youtube.com/watch?v=v7dGifwCvtw
> 
> It also did it when i was simply controlling the 3rd channel.

  OK, now I understand it. But this usage is not expected usage. When
some trim/key is set to MOMentary, then servo value is forced to the
state of this trim/key. So when You change it with anothet trim/key,
it is forced back to MOMentary state.
  If I change MOMentary code to change value only when state changes
(I am considering it), then it will work but will return to 0 after
MOMentary is depressed.
  So You must wait for those other changes which will allow to use
MOMentary to set end-values and return back to previous value as we
talked about.

**Comment by losikid** [comment]
Yes i know when momentary is depressed...but at the end of the menu, i send it to -60% with my end function, my step rate set at 20%. I didn't touch any keys and it moved back to zero after is stopped displaying the -60%. I tried this twice asi thought i may have been my fault the first time...it needs to hold position till its told otherwise when using the other functions besides momentary. 

My other comments via pm's about the mom and another key working together is not related to this issue.

How about you try it. Hook up a servo to ch 3, map a switch to ch 3 with a step rate of 20, Bump it up a few times till it gets somewhere and wait a few seconds. When the % disappears from the screen the servo will go back to center.

**Comment by losikid** [comment]
err, they need to put comment and close on the right side

**Comment by losikid** [comment]
Actually i think i mis understood you.

**Comment by losikid** [comment]
It is perfect right now momentary wise, when depressed goes to end points, when nothing depressed returns to center. However there needs to be a way when using two buttons to control a channel or function that its non depressed state can be overridden, also having it return to previous state after let off...but this will need to be an option. return to previous state or return to center.

**Comment by semerad** [comment]
> Yes i know when momentary is depressed...but at the end of the menu, i

  I know how I programmed it and this is correct. In current firmware
it was not expected to map MOMentary and non-MOMentary to same function.
That is why it is not working as You expected. It doesn't depend if
MOMentary is pressed or released, value of this is forced to servo
(You can think about it that it is 2/3 state analog channel).
  And it is done after that popup disappear because then it returns to
loop where it is forced.
  Again, this will not work now because when some channel/value is set
to MOMentary, it was programmed so servo value represents this button
"STATE", so it is not possible to change it with another button (which
is only temporary change).

**Comment by semerad** [comment]
> It is perfect right now momentary wise, when depressed goes to end
> points, when nothing depressed returns to center. However there needs
> to be a way when using two buttons to control a channel or function
> that its non depressed state can be overridden, also having it return
> to previous state after let off...but this will need to be an option.
> return to previous state or return to center.

  But this is new functionality which is not in current firmware. I
didn't expect somebody will want to combine MOMentary and non-MOMentary
setting for one channel/mix/...  MOMentary is now something like
steering wheel/throttle/stick .
  This all must be newly programmed.

**Comment by losikid** [comment]
Yes i know in current firmware this can't be done...i'm fairly new to code sharing sites, but i thought issues page was for bugs to fix in future revisions.

The reason i combined it this way, is because i didn't like the long press time, as i use dig alot. I'll go in and out of front dig (100% mix) so many time in one climb you can't count them or tell if i do as its simply to load or unload the suspension. So for me, having to wait a second to get dig was kinda frustrating the first 30 minutes or so of testing. So i mapped another switch for mom. The positioning of the switch compared to the radio i built are way different so my reflexes wern't nearly as good, but i liked it much better than the the long press...and i have my axles geared to always overdrive slightly so i wasn't running bias mixing while testing. I tried it but didn't leave it sit. So it surprised me when i got back to the house to take a vid of the mixing features.

But i think in future revisions, some changes to the mom function would be nice...like you mentioned above make it so it only changes when state is changed, I'm not sure if the switches/buttons are analog or not, if they are possibly have a analog mom and a digital mom...so in analog they can be replaced with pots or non rtc switched. But in digital it doesn't hold override all the positions, just when it changes it'll move the position. It still needs to return to center though if the switch/button is release...otherwise it be no different than the other functions.

**Comment by semerad** [comment]
> Yes i know in current firmware this can't be done...i'm fairly new to
> code sharing sites, but i though issues page was for bugs to fix in
> future revisions.

  But new features are not usualy called bugs :-)

**Comment by losikid** [comment]
Well at first i didn't realize it was supposed to do that...and in my case it kinda was a bug...So i'll wait patiently for a new revision. Will this be a hard feature to add?

**Comment by semerad** [comment]
> Well at first i didn't realize it was supposed to do that...and in my
> case it kinda was a bug...So i'll wait patiently for a new revision.
> Will this be a hard feature to add?

  I must change representation of key-mapping to allow this more
functionality and change corresponding code. I did similar config
change before and it is not so hard. Only all this key stuff will
require to check it whole again.
