### ISSUE TITLE
More cars less models

### ISSUE THREAD

**Issue by Kubikx** [semerad/gt3b#10]
Hi, can you create new fw where each model control different car.

I mean when I pair it with two cars and switch on both cars I will control only one of them chosen by model.

Thanks

**Comment by semerad** [comment]
> Hi, can you create new fw where each model control different car.
> 
> I mean when I pair it with two cars and switch on both cars I will control only one of them chosen by model.

  How do You think it will work ? Both receivers will be still receiving
same channel data.
  And it is not possible to change tramsmitter pairing data. It is
provided by HF module which is out of scope of firmware.

**Comment by Kubikx** [comment]
Spektrum use "ModelMatch" :http://www.spektrumrc.com/Technology/modelmatch.aspx
example:
http://www.spektrumrc.com/Products/Default.aspx?ProdId=SPM3300

each model on TX control different receiver

**Comment by semerad** [comment]
> Spektrum use "ModelMatch" :http://www.spektrumrc.com/Technology/modelmatch.aspx

  Did You read there this ? :

"ModelMatch assigns each receiver its own unique code when it's bound to
your Spektrum transmitter."

> example:
> http://www.spektrumrc.com/Products/Default.aspx?ProdId=SPM3300
> 
> each model on TX control different receiver

  They are using unique codes which are set to transmitter HF module
and receivers. But we don't have such possibility at GT3B.
  In GT3B it works that way, that radio HF module has some unique code
(which cannot be changed from GT3B firmware) and during bind receiver
learns this unique code (and then reacts only to this radio).
  So this functionality cannot be done in GT3B.

**Comment by Kubikx** [comment]
You think that is impossible with GT3B.   :-(
Thanks for fast answers.
