### ISSUE TITLE
Radio doesn't except input w/ ch change

### ISSUE THREAD

**Issue by losikid** [semerad/gt3b#2]
I have a feeling its just the nature of it. But when a 0.3.x firmware is already loaded to the radio, and if you change the ch version of the firmware it will make the radio mostly non responsive. I'm not sure if this can be fixed or not in the future, but i figured i'd let you know. I was able to repeat my results many times. I always had to revert back to 0.2.0 then go to 0.3.2 in order to change the amount of ch's i wanted to use in 0.3.2

**Comment by semerad** [comment]
> I have a feeling its just the nature of it. But when a 0.3.x firmware
> is already loaded to the radio, and if you change the ch version of
> the firmware it will make the radio mostly non responsive. I'm not
> sure if this can be fixed or not in the future, but i figured i'd let
> you know. I was able to repeat my results many times. I always had to
> revert back to 0.2.0 then go to 0.3.2 in order to change the amount of
> ch's i wanted to use in 0.3.2

  I will try it when I return from holidays. It looks like something is
not correctly initialized. Try to erase EEPROM after this change when
You have irresponsible radio, this will erase whole configuration.
Do it in STVP in "DATA MEMORY" tab and write those default zeroes to radio.
If this will help, than it is sure, that something was badly initialized.
And because there is no other thing which can be different, this should
help :-) .

**Comment by semerad** [comment]
> I have a feeling its just the nature of it. But when a 0.3.x firmware
> is already loaded to the radio, and if you change the ch version of
> the firmware it will make the radio mostly non responsive. I'm not
> sure if this can be fixed or not in the future, but i figured i'd let
> you know. I was able to repeat my results many times. I always had to
> revert back to 0.2.0 then go to 0.3.2 in order to change the amount of
> ch's i wanted to use in 0.3.2

  Hmm, I finally had time to test it. But it didn't behaved like You
wrote during my testing.
  It can be dependent at some setting. If it is doing it also after
Power-Off + Power-On cycle, read content of the "DATA MEMORY" and send
it to me together with version of firmware You have in the radio. I hope
that then it will be possible that at my unit it will be the same and I
will debug it then.
