### ISSUE TITLE
expo not working properly

### ISSUE THREAD

**Issue by whiskey29** [semerad/gt3b#5]
version 0.4.1
If I set expo on the positive side (+100 for extreme example) expo, turning left will be a lot more than turning left.

Shouldnt it be less servo movement nearer the center and move more near the end ?

**Comment by semerad** [comment]
> version 0.4.1
> If I set expo on the positive side (+100 for extreme example) expo, turning left will be a lot more than turning left.

  ??? "turning LEFT will be a lot more than turning LEFT"

> Shouldnt it be less servo movement nearer the center and move more near the end ?

  Yes, it should be this way. If it is not working correctly for You, it
can be because of steering wheel is not properly calibrated.

**Comment by whiskey29** [comment]
Thanks semerad.
I did recalibrate , its the one where 6 menus blinking right ?
I can take a video if that helps to point the issues.
