### ISSUE TITLE
Button Types are missing

### ISSUE THREAD

**Issue by losikid** [semerad/gt3b#8]
Finally got around to trying out the new firmware. And button types RS and EN are missing. I've tried the firmware on the gt3c and gt3b, i've tried both 0.5.1 and the 0.6.1 pre-release. I tried different buttons, functions, and i tried different models (ones in eeprom and ones in flash). No matter what i try, those button types are missing from the menu.

**Comment by semerad** [comment]
> Finally got around to trying out the new firmware. And button types RS
> and EN are missing. I've tried the firmware on the gt3c and gt3b, i've
> tried both 0.5.1 and the 0.6.1 pre-release. I tried different buttons,
> functions, and i tried different models (ones in eeprom and ones in
> flash). No matter what i try, those button types are missing from the
> menu.

  I did a little mistake (division by 4 instead of 3).
Download prerelease-0.6.1 again, it is corrected now.

**Comment by losikid** [comment]
Ok, i'll try it again here shortly

**Comment by losikid** [comment]
It fixed it
